export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const UPLOAD_POST_PHOTO_REQUEST = "UPLOAD_POST_PHOTO_REQUEST";
export const UPLOAD_POST_PHOTO_SUCCESS = "UPLOAD_POST_PHOTO_SUCCESS";
export const UPLOAD_POST_PHOTO_FAILURE = "UPLOAD_POST_PHOTO_FAILURE";

export const GET_POST_PHOTOS_REQUEST = "GET_POST_PHOTOS_REQUEST";
export const GET_POST_PHOTOS_SUCCESS = "GET_POST_PHOTOS_SUCCESS";
export const GET_POST_PHOTOS_FAILURE = "GET_POST_PHOTOS_FAILURE";

export const UPLOAD_POST_VIDEO_REQUEST = "UPLOAD_POST_VIDEO_REQUEST";
export const UPLOAD_POST_VIDEO_SUCCESS = "UPLOAD_POST_VIDEO_SUCCESS";
export const UPLOAD_POST_VIDEO_FAILURE = "UPLOAD_POST_VIDEO_FAILURE";

export const GET_POST_VIDEOS_REQUEST = "GET_POST_VIDEOS_REQUEST";
export const GET_POST_VIDEOS_SUCCESS = "GET_POST_VIDEOS_SUCCESS";
export const GET_POST_VIDEOS_FAILURE = "GET_POST_VIDEOS_FAILURE";

export const UPLOAD_POST_DOCUMENT_REQUEST = "UPLOAD_POST_DOCUMENT_REQUEST";
export const UPLOAD_POST_DOCUMENT_SUCCESS = "UPLOAD_POST_DOCUMENT_SUCCESS";
export const UPLOAD_POST_DOCUMENT_FAILURE = "UPLOAD_POST_DOCUMENT_FAILURE";

export const GET_POST_DOCUMENTS_REQUEST = "GET_POST_DOCUMENTS_REQUEST";
export const GET_POST_DOCUMENTS_SUCCESS = "GET_POST_DOCUMENTS_SUCCESS";
export const GET_POST_DOCUMENTS_FAILURE = "GET_POST_DOCUMENTS_FAILURE";
