import comradeIcon from "../../../dist/icons/comrade.svg";
import onlineIndicator from "../../../dist/icons/online.svg";
import driverIcon from "../../../dist/icons/driver.svg";
import organizationIcon from "../../../dist/icons/organisation.svg";
import employerIcon from "../../../dist/icons/employer.svg";

var userList = [
  {
    id: 1,
    name: "Johanna Keem ",
    username: "@kjohan",
    title: "Comrade",
    category: "",
    onlineIndicator: onlineIndicator,
    userType: comradeIcon,
    picture: "https://randomuser.me/api/portraits/men/77.jpg",
  },
  {
    id: 2,
    name: "Hailers ",
    username: "@Hailers",
    title: "Employer",
    // title: "Employer: Hailers",
    category: "",
    onlineIndicator: onlineIndicator,
    userType: employerIcon,
    picture: "https://randomuser.me/api/portraits/women/70.jpg",
  },
  {
    id: 3,
    name: "Jonson James",
    username: "Accountant",
    category: "",
    title: "Employer",
    // title:"Employer: Hailers >> Organisation: Team Lion",
    onlineIndicator: onlineIndicator,
    userType: organizationIcon,
    picture: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 4,
    name: "Jonlee Liu",
    username: "@Leejohn",
    category: "Driver",
    // title:"Employer: Hailers >> Organisation: Team Lion",
    title: "Employer",
    onlineIndicator: "",
    userType: driverIcon,
    picture: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 5,
    name: "Jonah Wee",
    username: "@Leejohn",
    category: "Driver",
    title: "Employer",
    // title: "Employer: Hailers >> Organisation: Team Spider",
    onlineIndicator: "",
    userType: driverIcon,
    picture: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 6,
    name: "Jonah Wee",
    username: "@Leejohn",
    category: "",
    title: "Comrade",
    onlineIndicator: "",
    userType: comradeIcon,
    picture: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 7,
    name: "Johanna Keem ",
    username: "@kjohan",
    title: "Comrade",
    category: "",
    onlineIndicator: onlineIndicator,
    userType: comradeIcon,
    picture: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 8,
    name: "Jonlee Liu",
    username: "@Leejohn",
    category: "Driver",
    title: "Employer",
    // title:"Employer: Hailers >> Organisation: Team Lion",
    onlineIndicator: "",
    userType: driverIcon,
    picture: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 9,
    name: "Hailers ",
    username: "@Hailers",
    title: "Employer",
    // title:"Employer: Hailers",
    category: "",
    onlineIndicator: onlineIndicator,
    userType: employerIcon,
    picture: "https://randomuser.me/api/portraits/men/57.jpg",
  },
  {
    id: 10,
    name: "Jonah Wee",
    username: "@Leejohn",
    category: "Driver",
    title: "Employer: Hailers >> Organisation: Team Spider",
    onlineIndicator: "",
    userType: driverIcon,
    picture: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  // {
  //   id: 7,
  //   name: "Kurtis",
  //   username: "@Elwyn",
  //   picture:"https://randomuser.me/api/portraits/men/24.jpg",
  // },
  // {
  //   id: 8,
  //   name: "Nicholas Runolf",
  //   username: "@Maxime",
  //   picture:"https://randomuser.me/api/portraits/women/82.jpg",
  // },
  // {
  //   id: 9,
  //   name: "Glenna Reichert",
  //   username: "@Delphine",
  //   picture:"https://randomuser.me/api/portraits/men/6.jpg",
  // },
  // {
  //   id: 10,
  //   name: "Clementina Jemima Jemima Jemima",
  //   username: "@Moriah",
  //   picture:"https://randomuser.me/api/portraits/women/32.jpg",
  // },
  // {
  //   id: 11,
  //   name: "Adan Alvaro",
  //   picture:"https://randomuser.me/api/portraits/men/32.jpg",
  //   username: "@Delphine",
  // }
];

export default userList;
