export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SET_SEARCH_DATA = "SET_SEARCH_DATA"
export const SET_SEARCH_PAGE_KEYWORD = "SET_SEARCH_PAGE_KEYWORD"
