export const  SET_DRIVER_SEARCH_FILTER='SET_DRIVER_SEARCH_LOCATION';
export const  DRIVER_SEARCH_REQUEST= 'DRIVER_SEARCH_REQUEST';
export const  DRIVER_SEARCH_SUCCESS= 'DRIVER_SEARCH_SUCCESS';
export const  DRIVER_SEARCH_FAILURE='DRIVER_SEARCH_FAILURE';
export const  SET_DRIVER_SEARCH_CURRENT_PAGE= 'SET_DRIVER_SEARCH_CURRENT_PAGE';