export const SET_AUTHENTICATE_EMPLOYER = "SET_AUTHENTICATE_EMPLOYER";
export const GET_EMPLOYER_PROFILE = "GET_EMPLOYER_PROFILE";

//JOB POSTS
export const ADD_JOB_POST = "ADD_JOB_POST";
export const REMOVE_EMPLOYER_PROFILE = "REMOVE_EMPLOYER_PROFILE";
export const EMPLOYER_UPDATE_JOB_POSTS = "EMPLOYER_UPDATE_JOB_POSTS";
export const GET_SINGLE_JOB_POST = "GET_SINGLE_JOB_POST";

// Business
export const GET_BUSINESS = "GET_BUSINESS";
export const UNSET_BUSINESS = "UNSET_BUSINESS";
export const GET_BUSINESS_JOB_POSTS = "GET_BUSINESS_JOB_POSTS";
export const APPLY_DRIVER_FOR_JOB = "APPLY_DRIVER_FOR_JOB";
export const SET_CURRENT_JOB_POSTS_PAGE = "SET_CURRENT_JOB_POSTS_PAGE";
