export const SET_AUTHENTICATE_USER = "SET_AUTHENTICATE_USER";
export const SET_AUTHENTICATION_ERRORS = "SET_AUTHENTICATION_ERRORS";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_FIRST_TIME = "UPDATE_FIRST_TIME";
