export const GET_DRIVER_PROFILE = "GET_DRIVER_PROFILE";

//job card types
export const UPDATE_JOB_CARDS = "UPDATE_JOB_CARDS";
export const REMOVE_DRIVER_PROFILE = "REMOVE_DRIVER_PROFILE";
export const SET_CURRENT_ACTIVE_CARD = "SET_CURRENT_ACTIVE_CARD";
export const DELETE_JOB_CARD = "DELETE_JOB_CARD";
export const GET_ALL_ACHIEVED_CARDS = "GET_ALL_ACHIEVED_CARDS";
export const DRIVER_PUBLIC_PROFILE_REQUESTED =
  "GET_DRIVER_PUBLIC_PROFILE_REQUESTED";
export const DRIVER_PUBLIC_PROFILE_SUCCESS = "DRIVER_PUBLIC_PROFILE_SUCCESS";
export const DRIVER_PUBLIC_PROFILE_FAILURE = "DRIVER_PUBLIC_PROFILE_FAILURE";
